spring:
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: 385b1626a43bb89831e7
            clientSecret: e7ca533cb0aba6bf6ff46cc37b1b5ad6c97a1ac8
          google:
            clientId: 585649674124-5ak5il01fjflsudcm8spjgcn09v96ir5.apps.googleusercontent.com
            clientSecret: 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
